In [116]:
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn import neighbors, metrics
from sklearn.preprocessing import LabelEncoder as Le

In [117]:
#KNN uniform vs distance
#Uniform gives the same level of importance to each neighbor
#Distnace gives high impoertnace to closer neighbors

In [118]:
data = pd.read_csv("/content/car.csv")
print(data)

      vhigh vhigh.1      2   2.1  small   low  unacc
0     vhigh   vhigh      2     2  small   med  unacc
1     vhigh   vhigh      2     2  small  high  unacc
2     vhigh   vhigh      2     2    med   low  unacc
3     vhigh   vhigh      2     2    med   med  unacc
4     vhigh   vhigh      2     2    med  high  unacc
...     ...     ...    ...   ...    ...   ...    ...
1722    low     low  5more  more    med   med   good
1723    low     low  5more  more    med  high  vgood
1724    low     low  5more  more    big   low  unacc
1725    low     low  5more  more    big   med   good
1726    low     low  5more  more    big  high  vgood

[1727 rows x 7 columns]


In [119]:
data.columns = ["buying", "maint", "doors", "persons", "lug_boot", "safety", "class"]
print(data)


     buying  maint  doors persons lug_boot safety  class
0     vhigh  vhigh      2       2    small    med  unacc
1     vhigh  vhigh      2       2    small   high  unacc
2     vhigh  vhigh      2       2      med    low  unacc
3     vhigh  vhigh      2       2      med    med  unacc
4     vhigh  vhigh      2       2      med   high  unacc
...     ...    ...    ...     ...      ...    ...    ...
1722    low    low  5more    more      med    med   good
1723    low    low  5more    more      med   high  vgood
1724    low    low  5more    more      big    low  unacc
1725    low    low  5more    more      big    med   good
1726    low    low  5more    more      big   high  vgood

[1727 rows x 7 columns]


In [120]:
X = data[["buying","maint","safety"]].values
y = data["class"]
print(X,y)

[['vhigh' 'vhigh' 'med']
 ['vhigh' 'vhigh' 'high']
 ['vhigh' 'vhigh' 'low']
 ...
 ['low' 'low' 'low']
 ['low' 'low' 'med']
 ['low' 'low' 'high']] 0       unacc
1       unacc
2       unacc
3       unacc
4       unacc
        ...  
1722     good
1723    vgood
1724    unacc
1725     good
1726    vgood
Name: class, Length: 1727, dtype: object


In [121]:
# Iterate over the columns of X and transform text data to numeric
encoders = [Le() for _ in range(X.shape[1])]

# Iterate over the columns of X and transform text data to numeric
for i in range(X.shape[1]):
    X[:, i] = encoders[i].fit_transform(X[:, i])

print(X)

[[3 3 2]
 [3 3 0]
 [3 3 1]
 ...
 [1 1 1]
 [1 1 2]
 [1 1 0]]


In [122]:
#Conversoin for Y with mapping
label_maping = {
    'unacc':0,
    'acc'  :1,
    'good' :2,
    'vgood':3
}

y= y.map(label_maping)
print(y)

0       0
1       0
2       0
3       0
4       0
       ..
1722    2
1723    3
1724    0
1725    2
1726    3
Name: class, Length: 1727, dtype: int64


In [123]:
knn = neighbors.KNeighborsClassifier(n_neighbors=25, weights="uniform")

In [124]:
 X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=.2)

In [125]:
knn.fit(X_train,y_train)
print(X_train)

[[1 0 2]
 [2 3 2]
 [2 0 0]
 ...
 [3 0 1]
 [0 2 2]
 [1 3 2]]


In [126]:
prediction = knn.predict(X_test)

In [127]:
accuracy = metrics.accuracy_score(y_test, prediction)
print(accuracy)

0.7543352601156069
